- README.md
Add my name, Alexandrea Mendoza, to the README.md file
> Update README.md with each team member's name

- README.md
- app/HomePage/page.tsx
Create Home Page template:
Header, body, and footer is visible on the page
Updated name on ReadME file
>  S26W-86, S26W-95

- README.md
- app/Login/page.tsx
- Created a template login page for the website according to the requirements of the JIRA subtask
- Additionally includes a (non-functional) option to sign in with Google
> S26W-114 Create Login Page Template 

- README.md
- app/Dashboard/page.tsx
New page for admin witha  simple, clean layout.
Placeholder items for Class Management, Calendar, Financials, Database, and Customer Info.
Each section shows a “placeholder” message
The page is mobile-friendly/scalable
> S26W-107: As an admin I want a simple owners' dashboard page 

- app/Login/page.tsx
- app/api/auth/[...nextauth]/route.ts
- middleware.ts
- package-lock.json
- package.json
- Successfully completed JIRA task S26W-116
- Login page is now functional with authentication for an admin account
- After successfully logging in with a valid Admin account, it will redirect to the Dashboard page
- Attempting to login with incorrect credentials or empty forms will clearly show an error
- **Dashboard is now protected, must sign in with the admin account to be able to access the dashboard**
- Remember me, reset password, sign up, and logging in with google are still not functional as of now
> S26W-104 As an owner I want to be able to log into my admin dashboard

- app/api/stripe/create-product/route.tsx
- app/api/stripe/delete-product/route.tsx
- app/api/stripe/list-products/route.tsx
- app/stripe-test/page.tsx
- package-lock.json
- package.json
add test page to input details into text fields
add functionality to create / list / delete items
connect site to stripe api
add /api/stripe to hold routes
> S26W-113 As an admin I want to be able to add and delete products

- app/Contact/page.tsx
- app/api/contacts/route.tsx
- app/lib/mailer.ts
- package-lock.json
- package.json
- Added email functionality to the Contact page using the Next.js framework.
- User inputs are gathered, validated on the frontend, and then sent to the backend for processing.
- After processing, the backend organizes the data into an HTML document and sends it via Nodemailer to the project’s group email address, where Gmail renders it as a readable, formatted message with a New contact form submission: header.
- Applied validation for required fields, ensuring users cannot send the message until all required fields are filled out, and optional fields are clearly labeled.
- Utilized environmental variables to secure and manage sensitive project email data.
> S26W-49  As a customer I want to be able to contact the owner

- app/Contact/page.tsx
- app/api/contacts/route.tsx
- app/lib/mailer.ts
- package-lock.json
- package.json
- Added email functionality to the Contact page using the Next.js framework.
- User inputs are gathered, validated on the frontend, and then sent to the backend for processing.
- After processing, the backend organizes the data into an HTML document and sends it via Nodemailer to the project’s group email address, where Gmail renders it as a readable, formatted message.
- Applied validation for required fields, ensuring users cannot send the message until all required fields are filled out, and clearly labeled optional fields.
- Utilized environmental variables to secure and manage sensitive project email data.
> S26W-49 As a customer I want to be able to contact the owner - Corrected Task number/Title to align with Jira task in actual commit

- app/(CustomerPages)/class-catalog/page.tsx
- package-lock.json
commented areas of error for later fix
> Class Catalog Bug Fix

- app/(AdminPages)/Dashboard/components/CustomerManagementSection.tsx
- app/(AdminPages)/Dashboard/components/FinancialAnalytics.tsx
- app/(AdminPages)/Dashboard/page.tsx
- app/api/financial-analytics/route.tsx
- app/api/orders/route.tsx
- next.config.mjs
- package-lock.json
- package.json
Customer Order Access:
- Enable access to customer order information directly from the Customer Management page.
Order Details:
- Display the list of purchased items for each customer, including:
- Classes purchased
- Products purchased
Category Selection:
- Introduce a category button to filter between:
- "Classes"
- "Products"
Database Connection:
- Connect the search form to customer orders to ensure retrieved data is accurate and reflects purchase history.
> #63   S26W-63 As an admin I want to be able to manage customer orders

- app/ImageUpload/page.tsx
- utils/s3.ts
1. Image Upload Feature:
- Admins must be able to upload images from their local machine.
- Provide both a file browsing option and a drag-and-drop interface.
2. Image Management:
- Store uploaded images securely.
- Allow renaming of uploaded images.
- Enable organization or categorization of images.
3. Website Integration:
- Ensure this image upload function can be called and used in various parts of the website.
4. Image Access and Deletion:
- Provide an interface for viewing uploaded images.
> S26W-59: As an admin, I want to upload and access images on my website

- app/(CustomerPages)/GiftCards/page.tsx
1. Checkout Functionality.
2. Stripe POS API Integration.
3. Pricing Options: $50 - $200.
4. UI and Design Reference.
> S26W-69: As a customer I want to be able to purchase gift cards on the website

- app/(AdminPages)/Dashboard/components/ClassSection.tsx
- app/(AdminPages)/Dashboard/components/ItemSection.tsx
- app/(AdminPages)/Dashboard/components/ProductList.tsx
- app/(AdminPages)/Dashboard/components/productList/CourseCard.tsx
- app/(AdminPages)/Dashboard/components/productList/EditCourseForm.tsx
- app/(AdminPages)/Dashboard/components/productList/EditItemForm.tsx
- app/(AdminPages)/Dashboard/components/productList/ItemCard.tsx
- next.config.mjs
- package-lock 2.json
- package.json
UI Enhancements
- Product List: Improved layout, spacing, typography, and contrast for a modern, professional look. Added subtle design elements (shadows, rounded corners).
- Course & Item Pages: Redesigned forms and layouts for better usability and consistency. Standardized fonts, colors, and buttons.
- Buttons & Forms: Enhanced button clarity with labels and icons. Improved form usability with clear labels, error messages, and success indicators.
Refactoring & Component Separation
- Modular Architecture: Refactored large components into reusable, maintainable pieces with clear responsibilities.
- Improved Maintainability: Enhanced readability, structured file organization, and created a component library for scalable development.
> #50 As a developer, I want to edit the view of the product list GUI

- app/(CustomerPages)/StoreSearch/Components/ProductCard.tsx
- app/(CustomerPages)/StoreSearch/products/[id]/page.tsx
- package-lock.json
- package.json
- Product page is now dynamic which will take in data from a store page item from database and display all details of that item
- Added misc. functionality to be able to click on the product picture to zoom in
> #64 As a user, I want to view detailed product pages for each store item

- app/(AdminPages)/Dashboard/components/ClassCatalogManager.tsx
- app/(AdminPages)/Dashboard/components/Sidebar.tsx
- app/(AdminPages)/Dashboard/page.tsx
- app/(CustomerPages)/class-catalog/page.tsx
Definition of Done:
1. Class Catalog Manager:
- A page for managing class organization and displaying them on the customer-facing catalog.
- Includes functionality to rearrange classes so that more popular courses appear at the top.
2. Class Catalog Page:
- A dedicated page displaying class information for customers to browse and select classes.
- Information includes:
- Class name
- Description
- Prerequisites
3. Class Storage in Database:
- Ensure class data is stored in the database and properly linked to the class catalog page and class manager page.
- Prevent duplicate class entries in the database.
> #54: As an admin, I want to manage and display classes effectively on a catalog for customers

- app/(AdminPages)/Dashboard/components/NewsletterSection.tsx
- app/(AdminPages)/EmailBuilder/App/SamplesDrawer/index.tsx
- app/Components/NewsletterConfigForm.tsx
- app/api/cron/monthly-newsletter/route.ts
- app/api/newsletter-config/route.ts
- app/models/NewsletterConfig.ts
- vercel.json
Email Template Editor Functionality
Delete Button:
Add a button that is displayed next to each template on the side bar of the editor that allows the user to delete the appropriate template.
API routes for this functionality have already been created.
Monthly Newsletter Scheduler
Schedule Settings:
Allow the user to change the date at which the monthly newsletter is sent.
Monthly newsletter functionality is already implemented. 
Add a UI element on the Newsletter admin dashboard page that allows the admin to choose a date and time at which the monthly newsletter will be automatically sent.
Acceptance Criteria
User has ability to delete email templates.
UI element for schedule settings is present on functional on newsletter page.
> #136 As an admin, I want to be able to remove email templates and change the scheduling of the monthly newsletter with a UI component

- app/(CustomerPages)/CheckOut/success/page.tsx
- app/api/checkout/create-checkout-session/route.ts
- package-lock.json
- package.json
Payment API Integration with Stripe
Payment Processing:
Implement Stripe API to handle payment transactions securely.
Ensure the API captures payment details, processes transactions, and returns confirmation statuses.
Error Handling:
Display user-friendly error messages for failed transactions.
Log errors for backend review and troubleshooting.
Confirmation Notification:
Upon successful payment, display a confirmation message to the user.
Include transaction details such as amount, date, and payment method.
Shipping API Integration with Shippo
Label Generation:
Shipping labels can be properly generated from confirmed payments.
Error Handling:
Notify users if there are issues with shipping options or label generation.
Log errors for backend review and troubleshooting.
Connection Between …
> #51 As an Admin, I want my payment and shipping solutions to be connected

- app/(AdminPages)/Dashboard/page.tsx
- app/Components/Header2.tsx
- app/globals.css
Bug Fix: 
Commented out css that makes light-mode unreadable in globals.css
Removed unused active sections in Dashboard page.tsx
> Bug Fix: Light mode unreadable and unnecessary file read in Dashboard

- app/(AdminPages)/Dashboard/components/CoursesListSection.tsx
- app/(AdminPages)/Dashboard/components/ItemsListSection.tsx
- app/(AdminPages)/Dashboard/components/productList/CourseFilters.tsx
- app/(AdminPages)/Dashboard/components/productList/ItemFilters.tsx
- app/(AdminPages)/Dashboard/components/productList/SearchBar.tsx
- app/(CustomerPages)/StoreSearch/Components/Filters.tsx
- app/(CustomerPages)/StoreSearch/Components/ProductGrid.tsx
- app/(CustomerPages)/StoreSearch/Components/SearchBar.tsx
- app/(CustomerPages)/StoreSearch/page.tsx
- app/(CustomerPages)/class-catalog/Components/CourseFilters.tsx
- app/(CustomerPages)/class-catalog/Components/ProductGrid.tsx
- app/(CustomerPages)/class-catalog/page.tsx
- app/api/courses/route.ts
- app/api/items/route.ts
- Users can now search for an item/course that is available
- Admin can do the same on the dashboard
- Properly prompts the user if there are no products meeting the search criteria
- Handles searches efficiently in real-time
> #140 As an admin, I want a search bar on the product list pages on the dashboard as well as the store pages to easily search for an item or course

- app/(AdminPages)/Dashboard/components/productList/ClassViewModal.tsx
- app/(CustomerPages)/Contact/page.tsx
- app/(CustomerPages)/StoreSearch/Components/AddToCartButton.tsx
- app/(CustomerPages)/StoreSearch/Components/FilterConfig.ts
- app/(CustomerPages)/StoreSearch/Components/Filters.tsx
- app/(CustomerPages)/StoreSearch/Components/Pagination.tsx
- app/(CustomerPages)/StoreSearch/Components/ProductGallery.tsx
- app/(CustomerPages)/StoreSearch/Components/ProductGrid.tsx
- app/(CustomerPages)/StoreSearch/page.tsx
- app/(CustomerPages)/StoreSearch/products/[id]/page.tsx
- app/(CustomerPages)/policies/cancellation-policy/page.tsx
- app/Components/Footer2.tsx
- app/Components/Header2.tsx
- app/Components/NewsletterForm.tsx
- app/layout.tsx
- app/page.tsx
- next.config.mjs
- package-lock.json
- package.json
- tailwind.config.ts
- revamped header, footer, and homepage to reflect a more modern style
- imported new lightbox library for the product gallery/image
- some bugfixes
- additionally created a dedicated cancellation policy page taken from the client's main website
> #152 As a developer, I want to enhance the UI/UX of the home page + header/footer of the website

- app/(AdminPages)/EmailBuilder/App/InspectorDrawer/ConfigurationPanel/input-panels/ImageSidebarPanel.tsx
Now you can select an image instead of copy paste! Yay!
> added the S3ImageExplorer component to the newsletter editor

- app/(AdminPages)/Dashboard/components/ItemsListSection.tsx
- app/(AdminPages)/Dashboard/components/productList/ItemFilters.tsx
- app/(CustomerPages)/StoreSearch/Components/FilterConfig.ts
- app/(CustomerPages)/StoreSearch/Components/ProductCard.tsx
- app/(CustomerPages)/class-catalog/Components/CourseFilters.tsx
- app/(CustomerPages)/class-catalog/page.tsx
- ui fix for filters sidebar to properly display and stick on class-catalog page
- ui fix for product card to extend clickable area to entire card and not just the image for storepage
- modified default price variable to display all items for items list on dashboard
- modified stone certification variable to reflect database
> minor bugfixes for class-catalog, dashboard product list page

- app/(CustomerPages)/StoreSearch/Components/AddToCartButton.tsx
- app/(CustomerPages)/StoreSearch/Components/ProductGallery.tsx
- app/(CustomerPages)/StoreSearch/Components/ProductSpecifications.tsx
- app/(CustomerPages)/StoreSearch/Components/SuggestedProducts.tsx
- app/(CustomerPages)/StoreSearch/page.tsx
- app/(CustomerPages)/class-booking/page.tsx
- app/(CustomerPages)/class-catalog/Components/ProductGrid.tsx
- app/(CustomerPages)/class-catalog/page.tsx
- app/Components/Header2.tsx
bugfuxes for ui for header, product gallery
additionally fixed the search bar for the class catalog, added date filtering
> various bugfixes

- app/(CustomerPages)/OpenLab/Booking/page.tsx
- app/(CustomerPages)/OpenLab/page.tsx
- app/(CustomerPages)/StoreSearch/Components/ProductGrid.tsx
- app/(CustomerPages)/StoreSearch/Components/SuggestedProducts.tsx
- app/(CustomerPages)/calendar/Components/Calendar.tsx
- app/(CustomerPages)/class-booking/page.tsx
- app/(CustomerPages)/class-catalog/Components/ProductGrid.tsx
- app/Calender/page.tsx
- optimized open lab and calendar page for mobile
- several bugfixes
- added more obvious validation errors for fields in class booking page
note: not too much was actually changed on the calendar page, i just used prettier to reformat the code so that's why there's so many deletions for that file (even though not much was rly deleted)
> various bugfixes and mobile optimizations
